const express = require("express");
const { UserModel } = require("../model/user.model");

const userRouter = express.Router();
/**
 * @swagger
 * components:
 *  schemas:
 *      User:
 *          type: object
 *          properties:
 *              id:
 *                  type: string
 *                  description: The autogenerated number by mongodb
 *              name:
 *                  type: string
 *                  description: user's name
 *              age:
 *                  type: integer
 *                  description: user's age
 *              location:
 *                  type: string
 *                  description: user's location
 *              
 */
/**
 * @swagger
 * /users : 
 *  get:
 *      summary: This Route is used to get all the users data present in the DB
 *      tags: [Users]
 *      responses:
 *          200:
 *              description: The list of all the users
 *              content:
 *                  application/json:
 *                      schema:
 *                          type: array
 *                          item:
 *                              $ref:"#/components/schemas/User"                          
 *          400:
 *              description: Bad Request. 
 */
userRouter.get("/", async (req, res) => {
    const users = await UserModel.find();
    res.status(200).send(users)
})

/**
 * @swagger
 * /users/add:
 *  post:
 *      summary: To post the details of a new user
 *      tags: [Users]
 *      requestBody:
 *          required:true
 *      content:
 *          application/json:
 *              schema:
 *                  $ref: '#/components/schemas/User'                  
 *      responses:
 *          200:
 *              description: The user was successfully registered
 *              content:
 *                  application/json:
 *                      schema:
 *                          $ref: '#/components/schemas/User'
 *          500:
 *              description: Some server error
 *                                       
 */

userRouter.post("/add", async (req, res) => {
    const payload = req.body;
    const user = UserModel(payload);
    await user.save();
    res.status(200).send({ "msg": "User Successfully added" })
})

userRouter.patch("/update/:userID", (req, res) => {

})

userRouter.delete("/delete/:userID", (req, res) => {

})

module.exports = {
    userRouter
}